on:
  push:
    tags:
      - "v*"
name: Test and Release
jobs:
  npm-test:
    name: JavaScript Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        name: Install Node
        with:
          node-version: latest
      - run: corepack enable
      - run: pnpm --version
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
      - name: Run Tests
        run: pnpm run test -- --outputTruncateLength=500
  go-test:
    name: Go Tests
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version: 1.25.1
          check-latest: true
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
      - name: Install gRPC and Go
        run: |
          go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Run Go Tests with Coverage
        run: make test
  int-test:
    name: Integration Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v4
        name: Install Node
        with:
          node-version: latest
      - run: corepack enable
      - run: pnpm --version
      - uses: actions/setup-node@v4
        with:
          node-version: latest
          cache: "pnpm"
          cache-dependency-path: "**/pnpm-lock.yaml"
      - name: Install dependencies
        run: pnpm install
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Writing certs to file
        run: |
          echo "${{ secrets.TTL_KEY }}" > shared_key.pem
          echo "${{ secrets.TTL_CERT }}" > shared_cert.pem
      - name: Build
        uses: docker/bake-action@v6
        with:
          source: .
          load: true
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
      - name: Run Playwright tests
        run: docker compose up --exit-code-from playwright
      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
  buildx:
    needs: [go-test, npm-test, int-test]
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435 # v3.11.1
      - name: Login to DockerHub
        uses: docker/login-action@v3.5.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Log in to the Container registry
        uses: docker/login-action@v3.5.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v5
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            amir20/dozzle
            ghcr.io/amir20/dozzle
          tags: |
            type=raw,value=latest
            type=semver,pattern={{version}},prefix=v
            type=semver,pattern={{major}}.{{minor}},prefix=v
            type=semver,pattern={{major}},prefix=v
      - name: Writing certs to file
        run: |
          echo "${{ secrets.TTL_KEY }}" > shared_key.pem
          echo "${{ secrets.TTL_CERT }}" > shared_cert.pem
      - name: Build and push
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          tags: ${{ steps.meta.outputs.tags }}
          build-args: TAG=${{ steps.meta.outputs.version }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Create temporary containers for binary extraction
        run: |
          # Create containers for each platform without running them
          docker create --platform linux/amd64 --name dozzle-amd64 ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
          docker create --platform linux/arm64 --name dozzle-arm64 ${{ fromJSON(steps.meta.outputs.json).tags[0] }}
      - name: Extract binaries from containers
        run: |
          # Create directories for binaries
          mkdir -p binaries/amd64 binaries/arm64

          # Extract binaries from containers
          docker cp dozzle-amd64:/dozzle binaries/amd64/dozzle
          docker cp dozzle-arm64:/dozzle binaries/arm64/dozzle

          # Clean up containers
          docker rm dozzle-amd64 dozzle-arm64

          # Create archives for release
          cd binaries
          tar -czf dozzle-linux-amd64.tar.gz -C amd64 dozzle
          tar -czf dozzle-linux-arm64.tar.gz -C arm64 dozzle
      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-binaries
          path: binaries/*.tar.gz
          retention-days: 1
  git-release:
    needs: [buildx]
    name: Github Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Node
        uses: actions/setup-node@v4
      - name: Download binaries
        uses: actions/download-artifact@v4
        with:
          name: release-binaries
          path: binaries/
      - name: Release to Github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx changelogithub --assets binaries/*.tar.gz
